export type Locale = 'en' | 'kk' | 'ru';
export type Theme = 'light' | 'dark';

export const localeOptions: { value: Locale; label: string }[] = [
  { value: 'ru', label: 'Русский' },
  { value: 'kk', label: 'Қазақша' },
  { value: 'en', label: 'English' },
];

const messages = {
  en: {
    tagline: 'AI Sana business challenge marketplace', catalog: 'Catalog', createTask: 'Create task', proposals: 'Proposals', reset: 'Reset demo data',
    settings: 'Display settings', language: 'Language', theme: 'Theme', light: 'Light', dark: 'Dark',
    businessWorkspace: 'Business workspace', builderTitle: 'Turn a vague need into a task teams can actually start.', builderLead: 'Start with your own words. Task Doctor asks only about missing facts; it never makes business decisions or assigns a score.', roughDescription: 'Rough business description', roughPlaceholder: 'For example: We receive customer feedback from many channels and cannot see recurring problems quickly.', useDescription: 'Use this description', loadDemo: 'Load feedback-analysis demo', readinessPreview: 'Readiness is a preview. Only a confirmed version changes the catalog ranking.', taskDoctor: 'AI Task Doctor', doctorWorking: 'Task Doctor is reviewing…', confirmPublish: 'Confirm & publish',
    doctorHeading: 'Three questions to make this brief actionable', doctorLead: 'Answers are copied into the editable card exactly as you provide them.', applyAnswers: 'Apply answers to task card',
    openCatalog: 'Open catalog', catalogTitle: 'Better briefs rise. Every team can still apply.', catalogLead: 'Readiness changes ordering only. Every business-confirmed challenge remains open to student teams.', postChallenge: 'Post a challenge',
    noTasks: 'No published tasks yet', noTasksLead: 'Create a task, review it, and use Confirm & publish to add the first challenge.', readiness: 'Readiness', industry: 'Industry / topic', allReadiness: 'All readiness levels', allIndustries: 'All industries', showing: 'Showing {{shown}} of {{total}} published tasks', noMatches: 'No tasks match these filters', noMatchesLead: 'Every confirmed task remains in the catalog. Change a filter to view it.', clearFilters: 'Clear filters', openTopic: 'Open topic', forUsers: 'For: {{users}}', notSpecified: 'Not specified yet', openTask: 'Open task & submit proposal', editBusiness: 'Edit as business',
    businessDecision: 'Business decision', proposalsTitle: 'Humans choose the team.', proposalsLead: 'Review each proposal in full, then manually accept or reject it.', compareTask: 'Compare proposals for task', allTasks: 'All tasks', confirmedProgress: 'Confirmed team progress', points: 'points', noProposals: 'No proposals yet', noProposalsLead: 'Published tasks are visible in the catalog for student teams to explore and propose on.', skills: 'Skills', technologies: 'Technologies', interests: 'Interests', solutionIdea: 'Solution idea', plan: 'Plan', timeline: 'Timeline', prototype: 'Prototype', accept: 'Accept', reject: 'Reject', completedStage: 'Completed stage and evidence', confirmStage: 'Business: confirm completed stage (+10 points)', confirmedStage: 'Confirmed stage',
    humanConfirmation: 'Human confirmation', publishQuestion: 'Publish this task to the catalog?', publishLead: '{{title}} will become visible to every student team. Its readiness score changes ranking, never access.', keepEditing: 'Keep editing', publishTask: 'Publish task', studentProposal: 'Student proposal', chooseTeamLead: 'Choose your own team and provide the complete proposal for business review.', chooseTeam: 'Choose a team', studentTeam: 'Student team', prototypePlaceholder: 'https://…', timelinePlaceholder: 'For example: 3 days', cancel: 'Cancel', submitReview: 'Submit for business review', notSpecifiedClarify: 'Not specified — requires clarification',
    draft: 'DRAFT', working: 'WORKING', ready: 'READY', priority: 'PRIORITY', scoreConfirmed: 'Confirmed readiness', scorePreview: 'Readiness preview · confirm before publication', currentScore: 'Current score', potential: 'potentially', scoreBreakdown: 'Score breakdown', fastestImprove: 'What raises the score fastest', taskReady: 'Task is ready for student teams.',
    contextNeed: 'Context & need', dataMaterials: 'Data & materials', expectedResult: 'Expected result', successCriteria: 'Success criteria', constraints: 'Constraints', users: 'Users', businessInteraction: 'Business interaction', assistantName: 'AI Task Doctor', assistantHint: 'Task analysis and improvement', pending: 'Pending', accepted: 'Accepted', rejected: 'Rejected', shortDescriptionRequired: 'Add a short description first. The wording is kept as business-provided context.', demoLoaded: 'Demo brief loaded. Run AI Task Doctor, then replace or expand any details with your own facts.', doctorUnavailable: 'AI Task Doctor is unavailable. Continue editing the card directly.', needThreeAnswers: 'Answer all three questions before applying them to the card.', answersApplied: 'Answers applied. You can edit every field before publishing.', titleContextRequired: 'Provide a title and business description. Other missing details lower readiness but do not prevent publication.', proposalRequired: 'Choose a team and complete every proposal field.', urlRequired: 'Prototype URL must include http:// or https://.',
    draftExample: 'Example draft', chooseDraftExample: 'Choose one of 5 synthetic drafts',
    aiHowTitle: 'How AI Task Doctor works', aiMode: 'Mode', aiModeOffline: 'Local stub (no external model configured)', aiModeLive: 'External model', aiReasonNotConfigured: 'external endpoint is not configured', aiReasonNotCalled: 'not called yet', aiReasonSuccess: 'last reply accepted', aiReasonHttp: 'HTTP error — local questions used', aiReasonInvalid: 'invalid reply — local questions used', aiReasonTimeout: 'timeout — local questions used', aiReasonNetwork: 'network error — local questions used', aiPrompt: 'Prompt', aiInput: 'Request (JSON)', aiOutput: 'Reply (JSON)', aiOutputEmpty: 'Run AI Task Doctor to see the reply.', aiValidation: 'A reply is rejected and replaced by local questions on HTTP error, invalid JSON, unknown or duplicate field, empty or overlong question, fewer than 3 questions, or a 20-second timeout. Answers are copied only as typed by a person.',
    needsClarification: 'Needs clarification: {{count}} of 7 criteria missing', recommendTitle: 'Recommendations for a team', recommendLead: 'Matched by team interests, tasks with 40+ points only. The catalog below is never limited.', chooseTeamRecommend: 'Choose a team', recommendNone: 'No matching tasks with 40+ points yet — the whole catalog below is open.', decisionFinal: 'Decision is final: the stage has been confirmed.',
    storageUnreadable: 'Saved data could not be read. Demo data is shown; use Reset demo data to replace damaged storage.', storageInvalid: 'Invalid changes were not saved. Confirmed progress is final.', storageSessionOnly: 'Browser storage is unavailable or full. Changes remain in this session only.',
  },
  ru: {
    tagline: 'AI Sana — площадка бизнес-задач', catalog: 'Каталог', createTask: 'Создать задачу', proposals: 'Отклики', reset: 'Сбросить демо-данные',
    settings: 'Настройки отображения', language: 'Язык', theme: 'Тема', light: 'Светлая', dark: 'Тёмная',
    businessWorkspace: 'РАБОЧЕЕ ПРОСТРАНСТВО БИЗНЕСА', builderTitle: 'Превратите неясную потребность в задачу, с которой команды смогут начать работу.', builderLead: 'Начните своими словами. AI-диагностика задаёт вопросы только о недостающих фактах и не принимает решений за бизнес.', roughDescription: 'Краткое описание потребности', roughPlaceholder: 'Например: отзывы клиентов приходят из разных каналов, и мы не видим повторяющиеся проблемы.', useDescription: 'Использовать описание', loadDemo: 'Загрузить демо с анализом отзывов', readinessPreview: 'Рейтинг здесь предварительный. Только подтверждённая версия меняет место в каталоге.', taskDoctor: 'AI-диагностика задач', doctorWorking: 'AI-диагностика анализирует…', confirmPublish: 'Подтвердить и опубликовать',
    doctorHeading: 'Три вопроса, чтобы сделать задачу понятной команде', doctorLead: 'Ответы копируются в редактируемую карточку ровно в том виде, в котором вы их указали.', applyAnswers: 'Применить ответы к карточке',
    openCatalog: 'ОТКРЫТЫЙ КАТАЛОГ', catalogTitle: 'Лучшие брифы поднимаются выше. Откликнуться может каждая команда.', catalogLead: 'Рейтинг влияет только на порядок. Каждая подтверждённая бизнесом задача открыта студентам.', postChallenge: 'Опубликовать задачу',
    noTasks: 'Пока нет опубликованных задач', noTasksLead: 'Создайте, проверьте и подтвердите первую задачу для каталога.', readiness: 'Готовность', industry: 'Отрасль / тема', allReadiness: 'Все уровни готовности', allIndustries: 'Все отрасли', showing: 'Показано {{shown}} из {{total}} опубликованных задач', noMatches: 'Задач по этим фильтрам нет', noMatchesLead: 'Все подтверждённые задачи остаются в каталоге. Измените фильтр, чтобы увидеть их.', clearFilters: 'Сбросить фильтры', openTopic: 'Открытая тема', forUsers: 'Для: {{users}}', notSpecified: 'Пока не указано', openTask: 'Открыть задачу и подать отклик', editBusiness: 'Редактировать как бизнес',
    businessDecision: 'РЕШЕНИЕ БИЗНЕСА', proposalsTitle: 'Команду выбирает человек.', proposalsLead: 'Сравните полный текст каждого отклика и вручную примите или отклоните его.', compareTask: 'Сравнить отклики по задаче', allTasks: 'Все задачи', confirmedProgress: 'Подтверждённый прогресс команд', points: 'баллов', noProposals: 'Откликов пока нет', noProposalsLead: 'Опубликованные задачи доступны командам в каталоге.', skills: 'Навыки', technologies: 'Технологии', interests: 'Интересы', solutionIdea: 'Идея решения', plan: 'План', timeline: 'Срок', prototype: 'Прототип', accept: 'Принять', reject: 'Отклонить', completedStage: 'Выполненный этап и подтверждение', confirmStage: 'Бизнес: подтвердить этап (+10 баллов)', confirmedStage: 'Подтверждённый этап',
    humanConfirmation: 'ПОДТВЕРЖДЕНИЕ ЧЕЛОВЕКОМ', publishQuestion: 'Опубликовать задачу в каталоге?', publishLead: '{{title}} станет доступна всем студенческим командам. Рейтинг изменит позицию, но не доступ.', keepEditing: 'Продолжить редактирование', publishTask: 'Опубликовать задачу', studentProposal: 'ОТКЛИК КОМАНДЫ', chooseTeamLead: 'Самостоятельно выберите команду и заполните полный отклик для бизнеса.', chooseTeam: 'Выберите команду', studentTeam: 'Студенческая команда', prototypePlaceholder: 'https://…', timelinePlaceholder: 'Например: 3 дня', cancel: 'Отмена', submitReview: 'Отправить на рассмотрение бизнеса', notSpecifiedClarify: 'Не указано — нужно уточнение',
    draft: 'ЧЕРНОВИК', working: 'РАБОЧАЯ', ready: 'ГОТОВАЯ', priority: 'ПРИОРИТЕТНАЯ', scoreConfirmed: 'ПОДТВЕРЖДЁННАЯ ГОТОВНОСТЬ', scorePreview: 'ПРЕДВАРИТЕЛЬНАЯ ОЦЕНКА · ПОДТВЕРДИТЕ ПЕРЕД ПУБЛИКАЦИЕЙ', currentScore: 'Текущий рейтинг', potential: 'потенциально', scoreBreakdown: 'Расшифровка рейтинга', fastestImprove: 'Что быстрее повысит рейтинг', taskReady: 'Задача готова к работе со студенческими командами.',
    contextNeed: 'Контекст и потребность', dataMaterials: 'Данные и материалы', expectedResult: 'Ожидаемый результат', successCriteria: 'Критерии успеха', constraints: 'Ограничения', users: 'Пользователи', businessInteraction: 'Связь с бизнесом', assistantName: 'AI-диагностика задач', assistantHint: 'Анализ и улучшение задач', pending: 'На рассмотрении', accepted: 'Принята', rejected: 'Отклонена', shortDescriptionRequired: 'Сначала добавьте короткое описание. Формулировка сохраняется как контекст от бизнеса.', demoLoaded: 'Демо-бриф загружен. Запустите AI-диагностику, затем замените или дополните данные своими фактами.', doctorUnavailable: 'AI-диагностика недоступна. Продолжите редактировать карточку напрямую.', needThreeAnswers: 'Ответьте на все три вопроса, прежде чем переносить их в карточку.', answersApplied: 'Ответы перенесены. Перед публикацией можно изменить любое поле.', titleContextRequired: 'Укажите название и описание от бизнеса. Прочие пропуски снижают готовность, но не запрещают публикацию.', proposalRequired: 'Выберите команду и заполните все поля заявки.', urlRequired: 'URL прототипа должен начинаться с http:// или https://.',
    draftExample: 'Пример черновика', chooseDraftExample: 'Выберите один из 5 синтетических черновиков',
    aiHowTitle: 'Как работает AI-диагностика', aiMode: 'Режим', aiModeOffline: 'Локальная заглушка (внешняя модель не настроена)', aiModeLive: 'Внешняя модель', aiReasonNotConfigured: 'внешний endpoint не настроен', aiReasonNotCalled: 'ещё не вызывалась', aiReasonSuccess: 'последний ответ принят', aiReasonHttp: 'ошибка HTTP — использованы локальные вопросы', aiReasonInvalid: 'некорректный ответ — использованы локальные вопросы', aiReasonTimeout: 'таймаут — использованы локальные вопросы', aiReasonNetwork: 'ошибка сети — использованы локальные вопросы', aiPrompt: 'Промпт', aiInput: 'Запрос (JSON)', aiOutput: 'Ответ (JSON)', aiOutputEmpty: 'Запустите AI-диагностику, чтобы увидеть ответ.', aiValidation: 'Ответ отклоняется и заменяется локальными вопросами при ошибке HTTP, неверном JSON, неизвестном или повторном поле, пустом или слишком длинном вопросе, меньше чем 3 вопросах или таймауте 20 секунд. В карточку попадают только ответы человека.',
    needsClarification: 'Требует уточнения: не хватает {{count}} из 7 критериев', recommendTitle: 'Рекомендации для команды', recommendLead: 'По интересам команды, только задачи от 40 баллов. Каталог ниже при этом не ограничивается.', chooseTeamRecommend: 'Выберите команду', recommendNone: 'Подходящих задач от 40 баллов пока нет — весь каталог ниже открыт.', decisionFinal: 'Решение окончательное: этап подтверждён.',
    storageUnreadable: 'Сохранённые данные не удалось прочитать. Показаны демо-данные; нажмите «Сбросить демо-данные», чтобы заменить повреждённое хранилище.', storageInvalid: 'Некорректные изменения не сохранены. Подтверждённый прогресс окончателен.', storageSessionOnly: 'Хранилище браузера недоступно или заполнено. Изменения сохранятся только до закрытия вкладки.',
  },
  kk: {
    tagline: 'AI Sana — бизнес тапсырмалар алаңы', catalog: 'Каталог', createTask: 'Тапсырма құру', proposals: 'Өтінімдер', reset: 'Демо деректерін қалпына келтіру',
    settings: 'Көрсету баптаулары', language: 'Тіл', theme: 'Тақырып', light: 'Ашық', dark: 'Қараңғы',
    businessWorkspace: 'БИЗНЕС ЖҰМЫС КЕҢІСТІГІ', builderTitle: 'Жалпы қажеттілікті команда бастай алатын нақты тапсырмаға айналдырыңыз.', builderLead: 'Өз сөзіңізбен бастаңыз. AI тапсырма диагностикасы тек жетіспейтін деректерді сұрайды және бизнес үшін шешім қабылдамайды.', roughDescription: 'Қысқаша бизнес сипаттамасы', roughPlaceholder: 'Мысалы: клиент пікірлері әр арнадан келеді, ал қайталанатын мәселелерді жылдам көре алмаймыз.', useDescription: 'Осы сипаттаманы қолдану', loadDemo: 'Пікірлерді талдау демосын жүктеу', readinessPreview: 'Дайындық рейтингі алдын ала есептеледі. Тек расталған нұсқа каталогтағы орынды өзгертеді.', taskDoctor: 'AI тапсырма диагностикасы', doctorWorking: 'AI тапсырма диагностикасы талдап жатыр…', confirmPublish: 'Растау және жариялау',
    doctorHeading: 'Тапсырманы командаға түсінікті етуге арналған үш сұрақ', doctorLead: 'Жауаптар сіз берген түрде өңделетін карточкаға көшіріледі.', applyAnswers: 'Жауаптарды карточкаға қолдану',
    openCatalog: 'АШЫҚ КАТАЛОГ', catalogTitle: 'Жақсы брифтер жоғары көтеріледі. Әр команда өтінім бере алады.', catalogLead: 'Рейтинг тек реттілікке әсер етеді. Бизнес растаған әр тапсырма студенттерге ашық.', postChallenge: 'Тапсырманы жариялау',
    noTasks: 'Жарияланған тапсырмалар әзірге жоқ', noTasksLead: 'Каталогқа бірінші тапсырманы құрып, тексеріп, растаңыз.', readiness: 'Дайындық', industry: 'Сала / тақырып', allReadiness: 'Барлық дайындық деңгейі', allIndustries: 'Барлық салалар', showing: '{{total}} жарияланған тапсырманың {{shown}} көрсетілді', noMatches: 'Осы сүзгілерге сай тапсырма жоқ', noMatchesLead: 'Барлық расталған тапсырмалар каталогта қалады. Оларды көру үшін сүзгіні өзгертіңіз.', clearFilters: 'Сүзгілерді тазарту', openTopic: 'Ашық тақырып', forUsers: 'Кім үшін: {{users}}', notSpecified: 'Әзірге көрсетілмеген', openTask: 'Тапсырманы ашып, өтінім беру', editBusiness: 'Бизнес ретінде өңдеу',
    businessDecision: 'БИЗНЕС ШЕШІМІ', proposalsTitle: 'Команданы адам таңдайды.', proposalsLead: 'Әр өтінімді толық салыстырып, оны қолмен қабылдаңыз не қабылдамаңыз.', compareTask: 'Тапсырма бойынша өтінімдерді салыстыру', allTasks: 'Барлық тапсырмалар', confirmedProgress: 'Команданың расталған ілгерілеуі', points: 'ұпай', noProposals: 'Өтінімдер әзірге жоқ', noProposalsLead: 'Жарияланған тапсырмалар каталогта командаларға қолжетімді.', skills: 'Дағдылар', technologies: 'Технологиялар', interests: 'Қызығушылықтар', solutionIdea: 'Шешім идеясы', plan: 'Жоспар', timeline: 'Мерзім', prototype: 'Прототип', accept: 'Қабылдау', reject: 'Қабылдамау', completedStage: 'Орындалған кезең және дәлел', confirmStage: 'Бизнес: кезеңді растау (+10 ұпай)', confirmedStage: 'Расталған кезең',
    humanConfirmation: 'АДАМНЫҢ РАСТАУЫ', publishQuestion: 'Тапсырманы каталогқа жариялау керек пе?', publishLead: '{{title}} барлық студенттік командаларға қолжетімді болады. Рейтинг тек орнын өзгертеді.', keepEditing: 'Өңдеуді жалғастыру', publishTask: 'Тапсырманы жариялау', studentProposal: 'КОМАНДА ӨТІНІМІ', chooseTeamLead: 'Команданы өзіңіз таңдап, бизнеске арналған толық өтінімді толтырыңыз.', chooseTeam: 'Команданы таңдаңыз', studentTeam: 'Студенттік команда', prototypePlaceholder: 'https://…', timelinePlaceholder: 'Мысалы: 3 күн', cancel: 'Бас тарту', submitReview: 'Бизнес қарауына жіберу', notSpecifiedClarify: 'Көрсетілмеген — нақтылау қажет',
    draft: 'ЖОБА', working: 'ЖҰМЫСТАҒЫ', ready: 'ДАЙЫН', priority: 'БАСЫМ', scoreConfirmed: 'РАСТАЛҒАН ДАЙЫНДЫҚ', scorePreview: 'АЛДЫН АЛА БАҒА · ЖАРИЯЛАУ АЛДЫНДА РАСТАҢЫЗ', currentScore: 'Ағымдағы рейтинг', potential: 'ықтимал', scoreBreakdown: 'РЕЙТИНГ ТҮСІНДІРМЕСІ', fastestImprove: 'Рейтингті не тез көтереді', taskReady: 'Тапсырма студенттік командалармен жұмысқа дайын.',
    contextNeed: 'Мәтінмән және қажеттілік', dataMaterials: 'Деректер мен материалдар', expectedResult: 'Күтілетін нәтиже', successCriteria: 'Жетістік критерийлері', constraints: 'Шектеулер', users: 'Пайдаланушылар', businessInteraction: 'Бизнестің байланысы', assistantName: 'AI тапсырма диагностикасы', assistantHint: 'Тапсырмаларды талдау және жақсарту', pending: 'Қаралуда', accepted: 'Қабылданды', rejected: 'Қабылданбады', shortDescriptionRequired: 'Алдымен қысқа сипаттама қосыңыз. Мәтін бизнес берген контекст ретінде сақталады.', demoLoaded: 'Демо-бриф жүктелді. AI-диагностиканы іске қосып, деректерді өз фактіңізбен ауыстырыңыз не толықтырыңыз.', doctorUnavailable: 'AI-диагностика қолжетімсіз. Карточканы тікелей өңдеуді жалғастырыңыз.', needThreeAnswers: 'Жауаптарды карточкаға енгізер алдында барлық үш сұраққа жауап беріңіз.', answersApplied: 'Жауаптар енгізілді. Жариялар алдында әр өрісті өзгерте аласыз.', titleContextRequired: 'Атауы мен бизнес сипаттамасын енгізіңіз. Қалған бос орындар дайындықты азайтады, бірақ жариялауға кедергі емес.', proposalRequired: 'Команданы таңдап, өтінімнің барлық өрісін толтырыңыз.', urlRequired: 'Прототип URL-і http:// не https:// арқылы басталуы керек.',
    draftExample: 'Жоба мысалы', chooseDraftExample: '5 синтетикалық жобаның бірін таңдаңыз',
    aiHowTitle: 'AI диагностикасы қалай жұмыс істейді', aiMode: 'Режим', aiModeOffline: 'Жергілікті үлгі (сыртқы модель бапталмаған)', aiModeLive: 'Сыртқы модель', aiReasonNotConfigured: 'сыртқы endpoint бапталмаған', aiReasonNotCalled: 'әлі шақырылмаған', aiReasonSuccess: 'соңғы жауап қабылданды', aiReasonHttp: 'HTTP қатесі — жергілікті сұрақтар қолданылды', aiReasonInvalid: 'қате жауап — жергілікті сұрақтар қолданылды', aiReasonTimeout: 'уақыт бітті — жергілікті сұрақтар қолданылды', aiReasonNetwork: 'желі қатесі — жергілікті сұрақтар қолданылды', aiPrompt: 'Промпт', aiInput: 'Сұраныс (JSON)', aiOutput: 'Жауап (JSON)', aiOutputEmpty: 'Жауапты көру үшін AI диагностикасын іске қосыңыз.', aiValidation: 'HTTP қатесі, қате JSON, белгісіз не қайталанған өріс, бос не тым ұзын сұрақ, 3-тен аз сұрақ не 20 секунд күту кезінде жауап қабылданбайды және жергілікті сұрақтармен ауыстырылады. Карточкаға тек адамның жауаптары түседі.',
    needsClarification: 'Нақтылау қажет: 7 критерийдің {{count}} жетіспейді', recommendTitle: 'Командаға ұсыныстар', recommendLead: 'Команда қызығушылықтары бойынша, тек 40+ ұпайлы тапсырмалар. Төмендегі каталог шектелмейді.', chooseTeamRecommend: 'Команданы таңдаңыз', recommendNone: '40+ ұпайлы сәйкес тапсырма әзірге жоқ — төмендегі бүкіл каталог ашық.', decisionFinal: 'Шешім түпкілікті: кезең расталды.',
    storageUnreadable: 'Сақталған деректерді оқу мүмкін болмады. Демо деректер көрсетілді; бүлінген деректерді ауыстыру үшін «Демо деректерін қалпына келтіру» басыңыз.', storageInvalid: 'Қате өзгерістер сақталмады. Расталған ілгерілеу түпкілікті.', storageSessionOnly: 'Браузер жады қолжетімсіз не толы. Өзгерістер тек осы сессияда сақталады.',
  },
} as const;

export type TranslationKey = keyof typeof messages.en;

export function createTranslator(locale: Locale) {
  return (key: TranslationKey, values: Record<string, string | number> = {}) => messages[locale][key].replace(/{{(\w+)}}/g, (_, name) => String(values[name] ?? ''));
}

export function loadPreference<T extends string>(key: string, fallback: T): T {
  try {
    return (localStorage.getItem(key) as T | null) ?? fallback;
  } catch {
    return fallback;
  }
}

export function savePreference(key: string, value: string) {
  try {
    localStorage.setItem(key, value);
  } catch {
    // Presentation preferences are optional when local storage is unavailable.
  }
}

const industries: Record<string, Record<Locale, string>> = {
  SaaS: { en: 'SaaS', ru: 'SaaS', kk: 'SaaS' },
  Logistics: { en: 'Logistics', ru: 'Логистика', kk: 'Логистика' },
  Education: { en: 'Education', ru: 'Образование', kk: 'Білім беру' },
  Retail: { en: 'Retail', ru: 'Ритейл', kk: 'Бөлшек сауда' },
  Environment: { en: 'Environment', ru: 'Экология', kk: 'Экология' },
  'Customer experience': { en: 'Customer experience', ru: 'Клиентский опыт', kk: 'Клиент тәжірибесі' },
  AI: { en: 'AI', ru: 'AI', kk: 'AI' },
  Analytics: { en: 'Analytics', ru: 'Аналитика', kk: 'Аналитика' },
  Automation: { en: 'Automation', ru: 'Автоматизация', kk: 'Автоматтандыру' },
};

export function displayIndustry(industry: string, locale: Locale) {
  return industries[industry]?.[locale] ?? industry;
}
